const app=document.querySelector("#app");const sidebar=document.querySelector("#sidebar");document.querySelector("#year").textContent=new Date().getFullYear();
const PER_PAGE=6;
async function loadPosts(){let posts=[];try{const r=await fetch("posts.json");if(r.ok)posts=await r.json();}catch{}if(!posts.length){try{const data=document.querySelector("#posts-data").textContent;posts=JSON.parse(data);}catch{}}
return posts;}
function renderSidebar(posts){let tags=[...new Set(posts.flatMap(p=>p.tags||[]))];let years=[...new Set(posts.map(p=>new Date(p.date).getFullYear()))].sort((a,b)=>b-a);let html="<h3>Tags</h3>"+(tags.length?"<ul>"+tags.map(t=>`<li><a href="?tag=${t}">${t}</a></li>`).join("")+"</ul>":"<div class='muted'>No tags</div>");html+="<h3>Archives</h3>"+(years.length?"<ul>"+years.map(y=>`<li><a href='?year=${y}'>${y}</a></li>`).join("")+"</ul>":"<div class='muted'>No archives</div>");sidebar.innerHTML=html;}
function getParams(){let p=new URLSearchParams(location.search);return{post:p.get("post"),tag:p.get("tag"),year:p.get("year")};}
async function render(){const posts=await loadPosts();renderSidebar(posts);const {post,tag,year}=getParams();if(post){const p=posts.find(x=>x.slug===post);if(!p){app.innerHTML="<p>Not found</p>";return;}const r=await fetch(`posts/${p.slug}.md`);const md=await r.text();app.innerHTML=`<p><a href='./'>← Back</a></p><h1>${p.title}</h1><div>${md}</div>`;return;}
let list=posts;if(tag)list=list.filter(p=>p.tags&&p.tags.includes(tag));if(year)list=list.filter(p=>new Date(p.date).getFullYear()==year);list.sort((a,b)=>b.date.localeCompare(a.date));const page=parseInt(new URLSearchParams(location.search).get("page")||"1");const start=(page-1)*PER_PAGE;const paged=list.slice(start,start+PER_PAGE);
let html="<ul class='post-list'>"+paged.map(p=>{let img="";if(p.slug==="photo-entry")img="<img src='posts/sample.jpg' style='max-width:100%;margin:0.5rem 0'>";return `<li><h2 class='post-title'><a href='?post=${p.slug}'>${p.title}</a></h2><div class='post-meta'>${p.date}</div>${img}${p.description||""}</li>`}).join("")+"</ul>";app.innerHTML=html;}
render();